### ISSUE TITLE
Consider using Homu

### ISSUE THREAD

**Issue by remram44** [UV-CDAT/uvbot#1]
The only way to make sure the build is never broken at any time while pull requests are coming in is to atomically test & merge them. This is what Homu does.
- https://github.com/barosl/homu - Can be deployed on Travis or Buildbot
- http://homu.io/ - Homu as a service (tests with Travis)
- http://buildbot.rust-lang.org/homu/queue/rust - Example: queue for the [Rust](https://github.com/rust-lang/rust) project

**Comment by jbeezley** [comment]
I agree atomic testing is the way to go, unfortunately the build + test for this project takes too long for that to be possible.  We discussed strategies for handling this in the UV-CDAT issue list, but is an open problem.  Thanks for pointing out homu though.  That is new to me.

**Comment by remram44** [comment]
The full build of Rust (3 stages on all platforms) takes 2 hours; I don't think UV-CDAT takes that long? Also, that would still be a dozen merges per day...

**Comment by jbeezley** [comment]
At the moment, no it doesn't take that long.  The problem, as I understand it, is that you need to rebuild **every** open PR every time a merge takes place.  At the moment, there are 22 open PR's.  A merge would create a queue that would take about a day to process, assuming no other pushes took place.

I'm not saying that having so many open PR's is a good thing, it is just the way things are.

**Comment by remram44** [comment]
Some PRs might be early work not close to mergeable at all, or need a rebase. Why do you need to build them at all? There is no point. Put them in the queue when ready, and test and merge atomically...

This "test a merge of all branches" that was mentioned during the meeting is insane and totally unnecessary if you have a queue.

**Comment by jbeezley** [comment]
I'll have to read more about how homu works, but if you can stage things in a queue until they are ready, it sounds like it could work for us.  Thanks for the tip.

**Comment by doutriaux1** [comment]
used our in-house code in the end.
